Django_hello/urls.py
# Django_hello/urls.py

from django.conf.urls import include, url, patterns
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views


urlpatterns = [

    url(r'^$', include('main.urls')),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^photos/',include('photos.urls', namespace="photos")),
    url(r'^admin/', include(admin.site.urls)),

    #log-in
    url(r'^accounts/login/',
        auth_views.login,
        name='login',
        kwargs={'template_name': 'login.html'}),

    #log-out
    url(r'^accounts/logout/',
        auth_views.logout,
        name='logout',
        kwargs={'next_page': settings.LOGIN_URL}),
]

urlpatterns += static('/upload_files/', document_root=settings.MEDIA_ROOT)

blog/urls.py
# blog/urls.py

from django.conf.urls import url, patterns
from .views import index, title


urlpatterns = [

#    url(r'^$', index, name='index'),
    url(r'^$', title, name='title'),
]

main/urls.py
# main/urls

from django.conf.urls import include, url, patterns
from django.contrib import admin

from django.conf import settings

from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls, name='index'),
]

photos/urls.py
# photos/urls.py

from django.conf.urls import include, url, patterns
from django.contrib import admin


from .views import hello, detail, create



urlpatterns = [
    url(r'^$', hello, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', detail, name='detail'),
    url(r'^upload/$', create, name='create'),

    url(r'^admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('data published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

main/models.py
from django.db import models

# Create your models here.

photos/models.py
from django.db import models
from django.core.urlresolvers import reverse_lazy
from django.conf import settings


# Create your models here.

class Photo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    image = models.ImageField(upload_to='%Y/%m/%d/orig')
    filtered_image = models.ImageField(upload_to='%Y/%m/%d/filtered')
    content = models.TextField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        self.image.delete()
        self.filtered_image.delete()
        super(Photo, self).delete(*args, **kwargs)

    def get_absolute_url(self):
        url = reverse_lazy('detail', kwargs={'pk': self.pk})
        return url

photos/forms.py
from django import forms

from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('image', 'content', )

blog/views.py
#blog/views.py

from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'blog/index.html')

def title(request):
    return render(request, 'blog/title.html')

main/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'
# Create your views here.


#def index(request):
#    return render(request, 'title.html')

photos/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

from .models import Photo
from .forms import PhotoForm

# Create your views here.

#def hello(request):
#    return HttpResponse('안녕하세요!')

def hello(request):
    return render(request, 'photosHome.html')

def detail(request, pk):
    photo = get_object_or_404(Photo, pk=pk)

    #try:
    #    photo = Photo.objects.get(pk=pk)
    #except Photo.DoseNotExist:
    #    return HttpResponse('no picture')

    msg = (
        '<p>{pk}번의 사진을 보여줄게요</p>'.format(pk=photo.pk),
        '<p>주소는 {url}</p>'.format(url=photo.image.url),
        '<p><img src="{url}" /></p>'.format(url=photo.image.url),
    )
    return HttpResponse('\n'.join(msg))


def create(request):
    if request.method == "GET":
        form = PhotoForm()
    elif request.method == "POST":
        form = PhotoForm(request.POST, request.FILES)

        if form.is_valid():
            obj = form.save()
            return redirect(obj)

    ctx = {
        'form': form,
    }

    return render(request, 'edit.html', ctx)


def new_photo(request):
    if request.method == "GET":
        edit_form = PhotoEditForm()
    elif request.method == "POST":
        edit_form = PhotoEditForm(request.POST, request.FILES, request.user)

        if edit_form.is_valid():
            new_photo = edit_form.save(commit=False)
            new_photo.user = request.user
            new_photo.save()

            return redirect(new_photo.get_absolute_url())

Django_hello/templates/Django_hello/base.html
<!DOCTYPE html>
<html lang='ko'>

<head>
<title>{% block title %}Pytagram{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/base/css" %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

  <div id="header">
    <h2 class="maintitle"> Pytagram</h2>
    <h4 class="welcome">Welcome, <a href="#">wychoi</a> /
      <a href="#">Change Pwd</a> /
      <a href="#">Log out</a> /
    </h4>

  </div>


  <div id="header">
    <li><a href="#">Home</a></li>
    <li><a href="#">Blog</a></li>
    <li><a href="#">Photo</a></li>

    <li><a href="#">Add&bigtriangledown;</a>
      <ul>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Photo</a></li>
      </ul>
    </li>

    <li><a href="#">Change&bigtriangledown;</a>
      <ul>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Photo</a></li>
      </ul>
    </li>

    <li><a href="#">Archive</a></li>
    <li><a href="#">Search</a></li>
    <li><a href="#">Admin</a></li>

  </div>


{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>

</html>

Django_hello/templates/Django_hello/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% block content %}
<div id="content">
  This is Content area
</div>
{% endblock content %}


{% block footer %}
<div id="footer">
  This is Footer area
</div>
{% endblock footer %}

blog/templates/blog/index.html
Hello Django World

blog/templates/blog/title.html
<html>

<head>
<title>pystagram</title>
</head>

<body>

<div id="content">

    <h1>Picture List</h1>

    <ul>

    <li><h3><a href="http://www.naver.com"</a>Go to NAVER</h3></li>

    </ul>

</div>
</body>
</html>

main/templates/base.html
<!DOCTYPE html>
<html lang='ko'>

<head>
<title>{% block title %}Pytagram{% endblock %}</title>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}" />
<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />

</head>

<body>

  <div id="header">
    <h1 class="maintitle">Pytagram</h1>
    <h4 class="welcome">Welcome, <a href="#"> wychoi</a> /
      <a href="#">Change Passwd</a> /
      <a href="#">Log out</a> /
    </h4>

  </div>


  <div id="menu">
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'blog:title' %}">Blog</a></li>
    <li><a href="{% url 'photos:index' %}">Photo</a></li>

    <li><a href="#">Add&bigtriangledown;</a>
      <ul>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Photo</a></li>
      </ul>
    </li>

    <li><a href="#">Change&bigtriangledown;</a>
      <ul>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Photo</a></li>
      </ul>
    </li>

    <li><a href="#">Archive</a></li>
    <li><a href="#">Search</a></li>
    <li><a href="#">Admin</a></li>

  </div>


{% block content %}{% endblock %}

{% block footer %}{% endblock %}

</body>

</html>

main/templates/home.html
{% extends "base.html" %}

{% block title %}Main page of Pytagram{% endblock %}

{% block content %}
<div id="content">
  This is Content area
</div>
{% endblock content %}


{% block footer %}
<div id="footer">
  This is Footer area
</div>
{% endblock footer %}

main/templates/title.html
{% load staticfiles %}
<html>

<head>
    <title>Wooyong's pystagram</title>
    <style>
        div{
            background-color : skyblue;
            background-size  : contain;
        }
    </style>
</head>


<body>
{% load staticfiles %}
<img src = "{% static "main\img\kground.jpg"%}", style='border:10px; width:100%'>

<div id="content">

    <h1>Pystagram</h1>

    <ul>

    <li><h3><a href="http://0.0.0.0:8000/accounts/login"</a>Log-in</h3></li>
    <li><h3><a href="http://blog.naver.com/isac31"</a>Go to Wooyong's blog</h3></li>

    </ul>

</div>
</body>
</html>

photos/templates/edit.html
{% extends 'layout.html' %}

{% block content %}
<form
    method="POST"
    action=""
    enctype="multipart/form-data"
>
    {% csrf_token %}
    {{ form.as_p }}

    <p>
        <button type="submit">저장</button>
    </p>
</form>

{% endblock %}

photos/templates/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>{% block page_title %}Pystagram{% endblock %}</title>
    <meta charset="utf-8" />
    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
</head>

<body>
{% block content %}{% endblock %}
</body>

</html>

photos/templates/login.html
{% extends "layout.html" %}

{% block content %}

{% if form.errors %}
<p>ID나 비밀번호가 일치하지 않습니다.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>권한이 없는 페이지에 접근하였으니, 권한이 있는 계정으로 로그인하세요.</p>
    {% else %}
    <p>이 페이지를 보려면 로그인을 해야 합니다.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="로그인" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

photos/templates/photosHome.html
{% extends "base.html" %}
{% block title %}Photos page{% endblock %}

{% block content %}
<div id="content">
  <h1>My photos</h1>
</div>

{% endblock %}